name: Build plugi

on:
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    strategy:
      matrix:
        type: [Debug, Release]

    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v3

    - name: Install CMake
      uses: lukka/get-cmake@latest
      with:
        cmakeVersion: "~3.22.0"
        useLocalCache: true
        useCloudCache: false

    - name: Configure project
      run: cmake -Bbuild -DCMAKE_BUILD_TYPE=${{ matrix.type }}

    - name: Build configuration
      run: cmake --build build --parallel --config ${{ matrix.type }}
